-- Insert values
insert into section (name, path) values ('Section_1', '1');
insert into section (name, path) values ('Section_2', '1.1');
insert into section (name, path) values ('Section_3', '1.2');
insert into section (name, path) values ('Section_4', '1.2.1');
insert into section (name, path) values ('Section_5', '1.2.2');
insert into section (name, path) values ('Section_6', '1.2.3');
insert into section (name, path) values ('Section_7', '1.3.4');
insert into section (name, path) values ('Section_8', '1.3.4.1');
insert into section (name, path) values ('Section_9', '1.3.4.2');
insert into section (name, path) values ('Section_10', '1.3.4.3.1');
insert into section (name, path) values ('Section_11', '1.3.4.4.2.1');
insert into section (name, path) values ('Section_12', '1.3.4.5.2.2.1');

insert into product (name, section_id) values ('product 1', 1);
insert into product (name, section_id) values ('product 2', 2);
insert into product (name, section_id) values ('product 3', 3);
insert into product (name, section_id) values ('product 4', 4);
insert into product (name, section_id) values ('product 5', 5);
insert into product (name, section_id) values ('product 6', 6);
insert into product (name, section_id) values ('product 7', 7);
insert into product (name, section_id) values ('product 8', 8);
insert into product (name, section_id) values ('product 9', 9);
insert into product (name, section_id) values ('product 10', 10);
insert into product (name, section_id) values ('product 11', 11);
insert into product (name, section_id) values ('product 12', 12);
insert into product (name, section_id) values ('product 13', 1);
insert into product (name, section_id) values ('product 14', 1);
insert into product (name, section_id) values ('product 15', 1);
insert into product (name, section_id) values ('product 16', 12);
insert into product (name, section_id) values ('product 17', 12);
insert into product (name, section_id) values ('product 18', 12);
insert into product (name, section_id) values ('product 19', 12);
insert into product (name, section_id) values ('product 20', 12);
insert into product (name, section_id) values ('product 21', 8);
insert into product (name, section_id) values ('product 22', 8);
insert into product (name, section_id) values ('product 23', 8);
insert into product (name, section_id) values ('product 24', 5);
insert into product (name, section_id) values ('product 25', 5);
insert into product (name, section_id) values ('product 26', 5);
insert into product (name, section_id) values ('product 27', 5);
insert into product (name, section_id) values ('product 28', 5);
insert into product (name, section_id) values ('product 29', 5);
insert into product (name, section_id) values ('product 30', 6);
insert into product (name, section_id) values ('product 31', 6);
insert into product (name, section_id) values ('product 32', 6);
insert into product (name, section_id) values ('product 33', 6);
insert into product (name, section_id) values ('product 34', 6);
insert into product (name, section_id) values ('product 35', 4);
insert into product (name, section_id) values ('product 36', 4);
insert into product (name, section_id) values ('product 37', 4);